'use client';

import './globals.css';
import { Public_Sans } from 'next/font/google';
import { ApolloProvider } from '@apollo/client';
import client from '@src/graphql/client';
import ToasterProvider from '@src/providers/ToasterProvider';

// const inter = Inter({ subsets: ['latin'] });
const publicSans = Public_Sans({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <ToasterProvider />
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
