'use client';

import DefaultLayout from '@src/layouts/default/DefaultLayout';
import './globals.css';
import { Inter } from 'next/font/google';
import { ApolloProvider } from '@apollo/client';
import client from '@src/graphql/client';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
      // className={inter.className}
      >
        <ApolloProvider client={client}>
          {/* <UniversalNoticeModal /> */}
          <DefaultLayout>{children}</DefaultLayout>
        </ApolloProvider>
      </body>
    </html>
  );
}
