'use client';

// import '../globals.css';
import '../globals.css';
import { Inter } from 'next/font/google';
import { ApolloProvider } from '@apollo/client';
import client from '@src/graphql/client';
import AdminLayout from '@src/layouts/admin/AdminLayout';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function LayoutOne({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <AdminLayout>{children}</AdminLayout>
    </div>
  );
}
